const SELECT_SHOP = 'SELECT_SHOP'
const SET_SERCURITY = 'SET_LOADED_TOUCH_ID'
const SET_NOTIFY = 'COUNT_NOTIFY'
const SET_USERINFO = 'SET_USERINFO'
const SET_WORKINFO = 'SET_WORKINFO'
const SET_KPIINFO = 'SET_KPIINFO'
const SET_THEME = 'MODE'
const SET_FORMNOW = 'FORMNOW'
const SET_FORMSTATUS = 'FORMSTATUS'
const SET_PERMISSION = 'PERMISSION'
const SET_FILEINFO = 'FILEINFO'
const SET_BUSINESS_TRIPS = 'BUSINESSTRIPS'
const SET_KPI_SUMMARY = 'KPISUMMARY'
const SET_LIST_DATA_STORE = 'LIST_DATA_STORE'
const EMPLOYEE_INFO = 'EMPLOYEE_INFO'
const REGION_DATA = 'REGION_DATA'
const MASTER_DATA = 'MASTER_DATA'
const SEARCH_DATA = 'SEARCH_DATA'
const SELECT_DATA = 'SELECT_DATA'
const IS_EDIT = 'IS_EDIT'
const IS_LOADING = 'IS_LOADING'
const IS_START_DISPLAY = 'IS_START_DISPLAY'
const ACTIVE_CAMERA = 'ACTIVE_CAMERA'
const SET_LOCATION_INFO = 'SET_LOCATION_INFO';
const CLEAR_LOCATION_INFO = 'CLEAR_LOCATION_INFO';
const SET_CAMERA_INFO = 'SET_CAMERA_INFO';
const SET_CAMERA_REPORT_INFO = 'SET_CAMERA_REPORT_INFO';
const CLEAR_CAMERA_INFO = 'CLEAR_CAMERA_INFO';
const CLEAR_CAMERA_REPORT_INFO = 'CLEAR_CAMERA_REPORT_INFO';
const SET_CACHE_DATA = 'SET_CACHE_DATA';
const CLEAR_CACHE_DATA = 'CLEAR_CACHE_DATA';
const DASHBOARD_FILTER = 'DASHBOARD_FILTER';
const SET_TOKEN_AUTO_LOGIN = 'SET_TOKEN_AUTO_LOGIN';

export const ACTION = {
    SELECT_SHOP,
    SET_SERCURITY,
    SET_NOTIFY,
    SET_USERINFO,
    SET_WORKINFO,
    SET_KPIINFO,
    SET_THEME,
    SET_FORMNOW,
    SET_FORMSTATUS,
    SET_PERMISSION,
    SET_FILEINFO,
    SET_BUSINESS_TRIPS,
    SET_KPI_SUMMARY,
    SET_LIST_DATA_STORE,
    EMPLOYEE_INFO,
    REGION_DATA,
    MASTER_DATA,
    SEARCH_DATA,
    SELECT_DATA,
    IS_EDIT,
    IS_LOADING,
    IS_START_DISPLAY,
    ACTIVE_CAMERA,
    SET_LOCATION_INFO, CLEAR_LOCATION_INFO,
    SET_CAMERA_INFO, SET_CAMERA_REPORT_INFO, CLEAR_CAMERA_INFO, CLEAR_CAMERA_REPORT_INFO,
    SET_CACHE_DATA, CLEAR_CACHE_DATA,
    DASHBOARD_FILTER,
    SET_TOKEN_AUTO_LOGIN
}