export const CHECK_IN = 0;
export const CHECK_OUT = 1;
const NOTE = 'NOTE';
const SELECT = 'SELECT';
const OT = 'OT';
const SHOPNOTE = 'SHOPNOTE';
const NOTEREPORT = 'NOTEREPORT';
const KTC = 'KTC';
const NOTEKPI = 'NOTEKPI';
export const ATTENDANT = {
  NOTE,
  SELECT,
  OT,
  SHOPNOTE,
  NOTEREPORT,
  KTC,
  NOTEKPI,
};
// SELLOUT
export const typemodal = {
  SHOP_MODAL: 'SHOP_MODAL',
  PRODUCT_MODAL: 'PRODUCT_MODAL',
  COMPETITOR_MODAL: 'COMPETITOR_MODAL',
  CATEGORY_MODAL: 'CATEGORY_MODAL',
  SUB_CATEGORY_MODAL: 'SUB_CATEGORY_MODAL',
  SEGMENT_MODAL: 'SEGMENT_MODAL',
  SUB_SEGMENT_MODAL: 'SUB_SEGMENT_MODAL',
  COLOR_MODAL: 'COLOR_MODAL',
  GENDER_MODAL: 'GENDER_MODAL',
  AGE_MODAL: 'AGE_MODAL',
  QUANTITY: 'QUANTITY',
  PRICE: 'PRICE',
  CUSTOMER: 'CUSTOMER',
  PHONE: 'PHONE',
  CUSTOMER_ADDRESS: 'CUSTOMER_ADDRESS',
  SCAN_IMEI: 'SCAN_IMEI',
  NOTE: 'NOTE',
};
export const PROGRAM_KEY = {
  IS_DOING_REVIEW: 'IS_DOING_REVIEW',
  DATA_EVALUATE: 'DATA_EVALUATE',
  DELIVERY_SLIP: 'DELIVERY_SLIP',
};
// SHOPINFO
